local_costmap:
  update_frequency: 20.0
  publish_frequency: 20.0
  transform_tolerance: 5.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  origin_x: -3
  origin_y: -3
  resolution: 0.1
  inflation_radius: 0.6
  plugins:
      - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
