obstacle_range: 8.0
raytrace_range: 8.5
#footprint: [[0.75, 0.75], [0.75, -0.75], [-0.1, -0.1], [-0.1, 0.1]]
footprint: [[0.16, 0.16], [0.16, -0.16], [-0.16, -0.16], [-0.16, 0.16]]
map_topic: /map
subscribe_to_updates: true
global_frame: map
transform_tolerance: 1
robot_base_frame: base_link
always_send_full_costmap: true
static_layer:
    map_topic: /map
    subscribe_to_updates: true
inflation:
    inflation_radius: 0.55
    cost_scaling_factor: 50
plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: lazer_sensor, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 5.0, obstacle_range: 8.0, raytrace_range: 8.5}
