global_costmap:
  update_frequency: 20.0
  publish_frequency: 20.0
  transform_tolerance: 5.0
  width: 15.0
  height: 15.0
  origin_x: -15.0
  origin_y: -15.0
  rolling_window: true
  inflation_radius: 2.5
  resolution: 0.1
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
